### ISSUE TITLE
requeriments for run this example

### ISSUE THREAD

**Issue by andresrivas1506** [nuclearace/socket.io-client-swift-example#1]
What I need for run this example? I have Xcode 6.2(6C131e), I download the project, I opened it with Xcode and I'm having 83 errors

**Comment by nuclearace** [comment]
It requires Xcode 6.3 beta

**Comment by mikezucc** [comment]
I am working on a version for 6.2, should I pull request it?

**Comment by nuclearace** [comment]
Hm. I'm not sure what would be gained. Xcode 6.3 was released a few days ago. And I updated the client for it.

I'm also not supporting swift 1.1 anymore. Since I assume most people would upgrade.

**Comment by mikezucc** [comment]
ok cool just saw that, I don't think theres that much difference ahah I had just adapted it from the beta version oh well
