### ISSUE TITLE
How to get this up and running?

### ISSUE THREAD

**Issue by JeanHules** [nuclearace/socket.io-client-swift-example#2]
I love that you made an example of how to use Swift/Socket. I am new to both and still wrapping my head around how they work. I have a simple node server up and running, but not sure I understand how this all works.

I see you provided the node setup, but I don't really know what to do after 'node index.js'.

**Comment by nuclearace** [comment]
You could try copying the xcodeproj into xcode

**Comment by coolgeng** [comment]
Do I need to setup socket server side as well? I see it try to connect 'localhost:8900' server. However, where is the server code?

**Comment by fre2ak** [comment]
You have to git clone --recursive https://github.com/nuclearace/socket.io-client-swift-example.git and then start the node server and build and run the xcode project.

**Comment by FangYiXiong** [comment]
but how to start the server?

**Comment by nuclearace** [comment]
Should just be `node index`
